### PR TITLE
Include parsing for login name.

### PR DESCRIPTION
**Pull request by davidgibbons**
Includes @login to the process object which includes the login running the process.

Also remove whitespace at the end of lines.

### CODE REVIEW

**Comment by jordansissel** [comment]
Haven't tested, but the code looks good to me :)

**Comment by jordansissel** [comment]
```
>> FOSL::Parser.new.lsof("-i :22").each { |pid, process| p process.login }
"jls"
"root"
"root"
```

lgtm.

**Comment by glensc** [comment]
maybe tag a release and upload new gem too?

**Comment by jordansissel** [comment]
Done 
```
Successfully registered gem: fosl (0.0.2)

```

**Comment by glensc** [comment]
no github tag push?

**Pull request merged**
